/**
 * Magenta Live Music -- Foundry VTT v12/v13 module.
 *
 * The music is generated by stream_player.py on the GM's machine, which serves
 * an endless MP3 at <serverUrl>/stream.mp3 and accepts prompts at
 * <serverUrl>/prompt. Every client plays that stream in its own <audio>
 * element, so a chat command from anyone changes what the whole table hears.
 *
 * Two browser realities shape this file:
 *   1. Autoplay is blocked until the user interacts with the page, so playback
 *      is armed on the first gesture rather than assumed to start.
 *   2. A page served over HTTPS cannot load an HTTP stream (mixed content), so
 *      the server URL has to match the scheme Foundry itself is served over.
 */

const MODULE_ID = "magenta-music";
const SOCKET = `module.${MODULE_ID}`;

let audio = null;
let armed = false;      // has a user gesture unlocked playback yet
let retryDelay = 1000;  // grows on repeated stream failures
let syncTimer = null;

// Whatever the browser buffers before it starts playing becomes permanent
// delay: from then on it receives and plays at the same rate, so the gap never
// closes on its own. Left alone that is several seconds between someone typing
// /music and the table hearing it. So we periodically skip forward to near the
// newest audio we have.
const LIVE_LAG_TARGET = 0.3;  // where we want to sit behind the live edge
const LIVE_LAG_LIMIT = 1.0;   // above this, correct it

/* ------------------------------------------------------------------ utils */

function log(...args) {
  console.log(`${MODULE_ID} |`, ...args);
}

function serverUrl() {
  return game.settings.get(MODULE_ID, "serverUrl").replace(/\/+$/, "");
}

function serverToken() {
  return (game.settings.get(MODULE_ID, "serverToken") ?? "").trim();
}

/** Token as a query string, for URLs that cannot carry a custom header. */
function tokenQuery(prefix = "?") {
  const t = serverToken();
  return t ? `${prefix}token=${encodeURIComponent(t)}` : "";
}

function effectiveVolume() {
  const own = game.settings.get(MODULE_ID, "volume");
  // Ride Foundry's ambient slider so the usual volume controls still work.
  let ambient = 1;
  try {
    ambient = game.settings.get("core", "globalAmbientVolume") ?? 1;
  } catch (e) { /* setting name varies by version; fall back to module volume */ }
  return Math.max(0, Math.min(1, own * ambient));
}

/* -------------------------------------------------------------- playback */

/** Seconds of already-received audio still queued ahead of the playhead. */
function liveLag() {
  if (!audio || !audio.buffered?.length) return 0;
  return audio.buffered.end(audio.buffered.length - 1) - audio.currentTime;
}

/** Skip forward to the live edge if we have drifted behind it. */
function syncToLive({ force = false } = {}) {
  if (!audio || audio.paused) return 0;
  const lag = liveLag();
  if (lag <= (force ? 0.5 : LIVE_LAG_LIMIT)) return lag;
  const target = audio.buffered.end(audio.buffered.length - 1) - LIVE_LAG_TARGET;
  try {
    audio.currentTime = target;
    log(`skipped ${lag.toFixed(1)}s of buffered delay`);
  } catch (err) {
    // Some browsers refuse to seek an endless stream. Fall back to playing
    // slightly fast until the gap closes; 6% is barely perceptible.
    log("seek refused, catching up with playback rate instead");
    audio.playbackRate = 1.06;
    setTimeout(() => { if (audio) audio.playbackRate = 1; }, lag * 17000);
  }
  return lag;
}

function stopPlayback() {
  if (syncTimer) { clearInterval(syncTimer); syncTimer = null; }
  if (audio) {
    audio.pause();
    audio.removeAttribute("src");
    audio.load();
    audio = null;
  }
}

function startPlayback({ restart = false } = {}) {
  if (!game.settings.get(MODULE_ID, "enabled")) return;
  if (audio && !restart) return;
  stopPlayback();

  // Cache-buster: without it a reconnect can resume a dead cached response.
  const url = `${serverUrl()}/stream.mp3?t=${Date.now()}${tokenQuery("&")}`;
  audio = new Audio(url);
  audio.preload = "none";
  audio.volume = effectiveVolume();
  audio.addEventListener("error", onStreamProblem);
  audio.addEventListener("ended", onStreamProblem);

  audio.play().then(() => {
    retryDelay = 1000;
    log("playing", url);
    // The initial buffer is built in the first couple of seconds; trim it once
    // it exists, then keep an eye on it in case a hiccup adds more.
    setTimeout(() => syncToLive(), 2500);
    if (syncTimer) clearInterval(syncTimer);
    syncTimer = setInterval(() => syncToLive(), 15000);
  }).catch((err) => {
    // Almost always NotAllowedError: no user gesture yet.
    log("autoplay blocked, waiting for a click:", err.name);
    armForGesture();
  });
}

function onStreamProblem() {
  if (!game.settings.get(MODULE_ID, "enabled")) return;
  log(`stream dropped, retrying in ${retryDelay}ms`);
  setTimeout(() => startPlayback({ restart: true }), retryDelay);
  retryDelay = Math.min(retryDelay * 2, 30000);
}

function armForGesture() {
  if (armed) return;
  armed = true;
  const resume = () => {
    document.removeEventListener("pointerdown", resume);
    document.removeEventListener("keydown", resume);
    armed = false;
    startPlayback({ restart: true });
  };
  document.addEventListener("pointerdown", resume, { once: true });
  document.addEventListener("keydown", resume, { once: true });
  ui.notifications?.info("Click anywhere to enable the live music.");
}

/* --------------------------------------------------------------- prompts */

async function sendPrompt(text, { raw = false, morph = null } = {}) {
  const headers = { "Content-Type": "application/json" };
  const token = serverToken();
  if (token) headers["X-Music-Token"] = token;
  const body = { text, raw };
  if (morph !== null) body.morph = morph;
  const res = await fetch(`${serverUrl()}/prompt`, {
    method: "POST",
    headers,
    body: JSON.stringify(body)
  });
  if (res.status === 403) throw new Error("server rejected the token");
  if (!res.ok) throw new Error(`server returned ${res.status}`);
  return res.json();
}

async function handleMusicCommand(argument) {
  const arg = argument.trim();

  if (!arg || arg === "help") {
    return postLocal(
      `<p><b>/music &lt;what is happening&gt;</b> — adapt the soundtrack.<br>` +
      `<b>/music raw &lt;style&gt;</b> — skip the AI rewrite.<br>` +
      `<b>/music status</b> — what is playing.<br>` +
      `<b>/music on</b> / <b>off</b> — your own playback only.</p>`);
  }

  if (arg === "off") { game.settings.set(MODULE_ID, "enabled", false); return; }
  if (arg === "on")  { game.settings.set(MODULE_ID, "enabled", true);  return; }

  if (arg === "sync") {
    const lag = syncToLive({ force: true });
    return postLocal(`<p>Skipped ${lag.toFixed(1)}s of buffered delay.</p>`);
  }

  const morph = arg.match(/^morph\s+([\d.]+)$/i);
  if (morph) {
    try {
      await sendPrompt("", { morph: Number(morph[1]) });
      return postLocal(`<p>Cross-fade set to ${morph[1]}s.</p>`);
    } catch (err) {
      return postLocal(`<p>Could not reach the music server: ${err.message}</p>`);
    }
  }

  if (arg === "status") {
    try {
      const res = await fetch(`${serverUrl()}/status${tokenQuery()}`);
      const d = await res.json();
      return postLocal(`<p>🎵 <b>${foundry.utils.escapeHTML(d.prompt)}</b><br>` +
        `<i>${d.listeners} listener(s), model ${d.model}, ` +
        `your delay ${liveLag().toFixed(1)}s</i></p>`);
    } catch (err) {
      return postLocal(`<p>Could not reach the music server: ${err.message}</p>`);
    }
  }

  const raw = arg.startsWith("raw ");
  const text = raw ? arg.slice(4).trim() : arg;
  if (!text) return;

  try {
    const data = await sendPrompt(text, { raw });
    // Everyone should see why the music changed, so this one is public.
    await ChatMessage.create({
      content: `<p>🎵 <i>${foundry.utils.escapeHTML(text)}</i><br>` +
               `<b>${foundry.utils.escapeHTML(data.style ?? text)}</b></p>`,
      speaker: { alias: "Music" }
    });
    // Everyone should be at the live edge for the change they just asked for.
    game.socket.emit(SOCKET, { action: "sync" });
    syncToLive();
  } catch (err) {
    postLocal(`<p>Music server unreachable (${foundry.utils.escapeHTML(err.message)}).` +
      ` Check the URL in module settings: <code>${serverUrl()}</code></p>`);
  }
}

function postLocal(content) {
  return ChatMessage.create({
    content,
    speaker: { alias: "Music" },
    whisper: [game.user.id]
  });
}

/* ----------------------------------------------------------------- hooks */

Hooks.once("init", () => {
  game.settings.register(MODULE_ID, "serverUrl", {
    name: "Music server URL",
    hint: "Where stream_player.py --serve is reachable from players' browsers. " +
          "Must use the same scheme as Foundry itself: an https Foundry page " +
          "cannot load an http stream.",
    scope: "world",
    config: true,
    type: String,
    default: `${window.location.protocol}//${window.location.hostname}:30001`
  });

  game.settings.register(MODULE_ID, "serverToken", {
    name: "Music server token",
    hint: "Must match --serve-token on the machine running stream_player.py. " +
          "Required whenever that machine is reachable from the internet; " +
          "leave blank if it is not.",
    scope: "world",
    config: true,
    type: String,
    default: ""
  });

  game.settings.register(MODULE_ID, "enabled", {
    name: "Play the live music",
    hint: "Turn off to silence the stream for yourself only.",
    scope: "client",
    config: true,
    type: Boolean,
    default: true,
    onChange: (value) => value ? startPlayback({ restart: true }) : stopPlayback()
  });

  game.settings.register(MODULE_ID, "volume", {
    name: "Music volume",
    scope: "client",
    config: true,
    type: Number,
    range: { min: 0, max: 1, step: 0.05 },
    default: 0.5,
    onChange: () => { if (audio) audio.volume = effectiveVolume(); }
  });
});

Hooks.once("ready", () => {
  game.socket.on(SOCKET, (data) => {
    if (data?.action === "sync") {
      startPlayback();     // no-op if already playing
      syncToLive();
    }
  });
  startPlayback();
  log("ready; streaming from", serverUrl());
});

// Foundry has no chat-command API, so intercept the message before it is sent.
Hooks.on("chatMessage", (chatLog, message) => {
  const match = message.match(/^\/music\b\s*(.*)/is);
  if (!match) return true;
  handleMusicCommand(match[1] ?? "");
  return false;  // stop Foundry from posting the raw "/music ..." text
});
