/**
 * Magenta Live Music -- Foundry VTT module.
 *
 * The music is generated by stream_player.py on the GM's machine, which serves
 * an endless MP3 at <serverUrl>/stream.mp3 and accepts prompts at
 * <serverUrl>/prompt. Every client plays that stream in its own <audio>
 * element, so a chat command from anyone changes what the whole table hears.
 *
 * The stream behaves like a playlist track wherever it can: it is routed
 * through Foundry's Music audio bus (so the core Music volume slider governs
 * it) and it gets a transport panel in the Playlists sidebar tab with the same
 * play / pause / stop controls a track has.
 *
 * Three browser realities shape this file:
 *   1. Autoplay is blocked until the user interacts with the page, so playback
 *      is armed on the first gesture rather than assumed to start.
 *   2. A page served over HTTPS cannot load an HTTP stream (mixed content), so
 *      the server URL has to match the scheme Foundry itself is served over.
 *   3. Routing a cross-origin stream through Web Audio requires CORS, and a
 *      proxy that strips those headers would silence the music -- so bus
 *      routing falls back to a plain element on the first sign of trouble.
 */

const MODULE_ID = "magenta-music";
const SOCKET = `module.${MODULE_ID}`;

/* Playback ---------------------------------------------------------------- */
let audio = null;         // the <audio> element carrying the stream
let bus = null;           // {ctx, source, gain} when routed through Foundry's mixer
let busDisabled = false;  // set once routing has failed; don't keep retrying
let armed = false;        // waiting on a user gesture to unlock playback
let retryDelay = 1000;    // grows on repeated stream failures
let syncTimer = null;
let startedAt = 0;        // when the current connection began playing

/* Server state ------------------------------------------------------------ */
let status = null;        // last successful GET /status payload, else null
let statusTimer = null;
let inflight = null;      // de-duplicates concurrent status polls

/* Sidebar panel ----------------------------------------------------------- */
let panel = null;
let draft = { text: "", raw: false };  // survives sidebar re-renders

// Whatever the browser buffers before it starts playing becomes permanent
// delay: from then on it receives and plays at the same rate, so the gap never
// closes on its own. Left alone that is several seconds between someone typing
// /music and the table hearing it. So we periodically skip forward to near the
// newest audio we have.
const LIVE_LAG_TARGET = 0.3;  // where we want to sit behind the live edge
const LIVE_LAG_LIMIT = 1.0;   // above this, correct it

const STATUS_POLL_MS = 6000;
const DEFAULT_PRESETS = [
  "Tavern | warm lute and fiddle, cheerful medieval tavern, light percussion",
  "Travel | gentle pastoral strings, rolling rhythm, hopeful woodwinds",
  "Dungeon | slow ominous drone, low strings, dark ambient, sparse percussion",
  "Combat | urgent orchestral strings, driving percussion, tense brass, fast",
  "Boss | huge choir, thunderous timpani, brass fanfare, epic orchestral",
  "Sorrow | solo cello, sparse piano, mournful and slow"
].join("\n");

/* ------------------------------------------------------------------ utils */

function log(...args) {
  console.log(`${MODULE_ID} |`, ...args);
}

function setting(key) {
  return game.settings.get(MODULE_ID, key);
}

function serverUrl() {
  return (setting("serverUrl") ?? "").trim().replace(/\/+$/, "");
}

function serverToken() {
  return (setting("serverToken") ?? "").trim();
}

/** Token as a query string, for URLs that cannot carry a custom header. */
function tokenQuery(prefix = "?") {
  const t = serverToken();
  return t ? `${prefix}token=${encodeURIComponent(t)}` : "";
}

function esc(value) {
  return foundry.utils.escapeHTML(String(value ?? ""));
}

/** Can this user change what the whole table hears? */
function canSteer() {
  if (game.user.isGM) return true;
  switch (setting("steerPermission")) {
    case "everyone": return true;
    case "trusted": return game.user.isTrusted;
    default: return false;
  }
}

/** Is the table meant to be listening right now? GM-controlled, world-wide. */
function tablePlaying() {
  return setting("playback") === "playing";
}

/** Is *this* client meant to be listening? Table state AND personal toggle. */
function shouldPlay() {
  return tablePlaying() && setting("enabled") && !!serverUrl();
}

/**
 * Volume in [0,1] for this client's own slider, curved the way Foundry curves
 * its own volume sliders so the two feel the same under the hand.
 */
function ownVolume() {
  const raw = setting("volume");
  const helper = foundry.audio?.AudioHelper ?? globalThis.AudioHelper;
  return helper?.inputToVolume ? helper.inputToVolume(raw) : raw;
}

/**
 * Volume to put on the element itself. When we are routed through Foundry's
 * Music bus the bus applies the global slider for us; when we are not, we have
 * to fold it in by hand so the core Music slider still does something.
 */
function elementVolume() {
  if (bus) return 1;
  let global = 1;
  try { global = game.settings.get("core", "globalPlaylistVolume") ?? 1; }
  catch (err) { /* setting absent on this version; module slider alone */ }
  return Math.max(0, Math.min(1, ownVolume() * global));
}

function applyVolume() {
  if (bus) bus.gain.gain.value = ownVolume();
  if (audio) audio.volume = elementVolume();
  updatePanel();
}

function parsePresets() {
  return (setting("presets") ?? "").split(/[\n;]+/)
    .map(line => line.trim()).filter(Boolean)
    .map(line => {
      const [label, ...rest] = line.split("|");
      const style = rest.join("|").trim();
      // A bare line with no "|" is both its own label and its own style.
      return { label: label.trim(), style: style || label.trim() };
    })
    .filter(p => p.label);
}

/* -------------------------------------------------------------- playback */

/**
 * Route the stream through Foundry's Music bus, so the core Music volume
 * slider governs it exactly as it governs a playlist track.
 *
 * The bus contexts only exist once AudioHelper has seen a user gesture, and
 * cross-origin audio only reaches Web Audio when the server sends CORS
 * headers. Either failure falls back to a plain element, which still plays.
 */
function connectToMusicBus(element) {
  if (busDisabled || !setting("useMusicBus")) return false;
  const ctx = game.audio?.music;
  if (!ctx?.createMediaElementSource) return false;
  try {
    const source = ctx.createMediaElementSource(element);
    const gain = ctx.createGain();
    gain.gain.value = ownVolume();
    source.connect(gain);
    gain.connect(ctx.gainNode ?? ctx.destination);
    bus = { ctx, source, gain };
    if (ctx.state === "suspended") ctx.resume();
    return true;
  } catch (err) {
    log("could not route through the Music bus:", err.message);
    busDisabled = true;
    return false;
  }
}

function disconnectFromMusicBus() {
  if (!bus) return;
  try { bus.source.disconnect(); bus.gain.disconnect(); } catch (err) { /* already gone */ }
  bus = null;
}

/** Seconds of already-received audio still queued ahead of the playhead. */
function liveLag() {
  if (!audio || !audio.buffered?.length) return 0;
  return audio.buffered.end(audio.buffered.length - 1) - audio.currentTime;
}

/** Skip forward to the live edge if we have drifted behind it. */
function syncToLive({ force = false } = {}) {
  if (!audio || audio.paused) return 0;
  const lag = liveLag();
  if (lag <= (force ? 0.5 : LIVE_LAG_LIMIT)) return lag;
  const target = audio.buffered.end(audio.buffered.length - 1) - LIVE_LAG_TARGET;
  try {
    audio.currentTime = target;
    log(`skipped ${lag.toFixed(1)}s of buffered delay`);
  } catch (err) {
    // Some browsers refuse to seek an endless stream. Fall back to playing
    // slightly fast until the gap closes; 6% is barely perceptible.
    log("seek refused, catching up with playback rate instead");
    audio.playbackRate = 1.06;
    setTimeout(() => { if (audio) audio.playbackRate = 1; }, lag * 17000);
  }
  return lag;
}

function stopPlayback() {
  if (syncTimer) { clearInterval(syncTimer); syncTimer = null; }
  disconnectFromMusicBus();
  if (audio) {
    audio.pause();
    audio.removeAttribute("src");
    audio.load();
    audio = null;
  }
  startedAt = 0;
  updatePanel();
}

function startPlayback({ restart = false } = {}) {
  if (!shouldPlay()) return;
  if (audio && !restart) return;
  stopPlayback();

  // Cache-buster: without it a reconnect can resume a dead cached response.
  const url = `${serverUrl()}/stream.mp3?t=${Date.now()}${tokenQuery("&")}`;
  audio = new Audio();
  audio.preload = "none";
  // Must be set before the source is assigned, and only when we actually want
  // Web Audio -- an unnecessary CORS requirement is a way to fail for nothing.
  const wantBus = !busDisabled && setting("useMusicBus") && !!game.audio?.music;
  if (wantBus) audio.crossOrigin = "anonymous";
  audio.src = url;
  audio.addEventListener("error", onStreamProblem);
  audio.addEventListener("ended", onStreamProblem);

  if (wantBus) connectToMusicBus(audio);
  audio.volume = elementVolume();

  audio.play().then(() => {
    retryDelay = 1000;
    startedAt = Date.now();
    log("playing", url, bus ? "(via the Music bus)" : "(direct)");
    // The initial buffer is built in the first couple of seconds; trim it once
    // it exists, then keep an eye on it in case a hiccup adds more.
    setTimeout(() => { if (setting("autoSync")) syncToLive(); }, 2500);
    if (syncTimer) clearInterval(syncTimer);
    syncTimer = setInterval(() => { if (setting("autoSync")) syncToLive(); }, 15000);
    updatePanel();
  }).catch((err) => {
    // Almost always NotAllowedError: no user gesture yet.
    log("autoplay blocked, waiting for a click:", err.name);
    armForGesture();
  });
  updatePanel();
}

function onStreamProblem() {
  if (!shouldPlay()) return;

  // A stream that dies almost immediately after we asked for CORS is the
  // signature of a proxy that drops the headers. Retry once without the bus
  // before falling into the backoff loop -- plain playback is worth more than
  // slider integration.
  if (bus && startedAt && (Date.now() - startedAt) < 4000) {
    log("stream failed right after connecting; retrying without Music bus routing");
    busDisabled = true;
    return startPlayback({ restart: true });
  }

  log(`stream dropped, retrying in ${retryDelay}ms`);
  setTimeout(() => startPlayback({ restart: true }), retryDelay);
  retryDelay = Math.min(retryDelay * 2, 30000);
  updatePanel();
}

function armForGesture() {
  if (armed) return;
  armed = true;
  const resume = () => {
    document.removeEventListener("pointerdown", resume);
    document.removeEventListener("keydown", resume);
    armed = false;
    startPlayback({ restart: true });
  };
  document.addEventListener("pointerdown", resume, { once: true });
  document.addEventListener("keydown", resume, { once: true });
  ui.notifications?.info("Click anywhere to enable the live music.");
  updatePanel();
}

/** React to a change in either the table-wide or the personal play state. */
function refreshPlaybackState() {
  if (shouldPlay()) startPlayback({ restart: true });
  else stopPlayback();
}

/**
 * Start or stop the music for the whole table (GM), or just for this client.
 * Non-GMs cannot write a world setting, so their button is a personal mute --
 * which is also what they want when the GM has the music running.
 */
async function setPlaying(playing, { table = game.user.isGM } = {}) {
  if (table && game.user.isGM) {
    await game.settings.set(MODULE_ID, "playback", playing ? "playing" : "stopped");
    // A player who had muted themselves stays muted; this only lifts the
    // table-wide stop.
    return;
  }
  await game.settings.set(MODULE_ID, "enabled", playing);
}

/* --------------------------------------------------------------- server */

async function fetchStatus({ quiet = true } = {}) {
  if (!serverUrl()) { status = null; updatePanel(); return null; }
  if (inflight) return inflight;
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 5000);
  inflight = fetch(`${serverUrl()}/status${tokenQuery()}`, { signal: controller.signal })
    .then(res => {
      if (!res.ok) throw new Error(`server returned ${res.status}`);
      return res.json();
    })
    .then(data => { status = data; return data; })
    .catch(err => {
      status = null;
      if (!quiet) throw err;
      return null;
    })
    .finally(() => { clearTimeout(timeout); inflight = null; updatePanel(); });
  return inflight;
}

/**
 * Send a prompt and/or tuning changes to the music server.
 * @param {string} text                Scene description, or "" to only retune.
 * @param {object} [options]
 * @param {boolean} [options.raw]      Skip the LLM rewrite, use these words.
 * @param {object} [options.tuning]    Any of morph/temp/topk/cfg/llm.
 */
async function sendPrompt(text, { raw = false, tuning = {} } = {}) {
  if (!serverUrl()) throw new Error("no music server URL is configured");
  const headers = { "Content-Type": "application/json" };
  const token = serverToken();
  if (token) headers["X-Music-Token"] = token;
  const res = await fetch(`${serverUrl()}/prompt`, {
    method: "POST",
    headers,
    body: JSON.stringify({ text, raw, ...tuning })
  });
  if (res.status === 403) throw new Error("the server rejected the token");
  if (!res.ok) throw new Error(`server returned ${res.status}`);
  const data = await res.json();
  if (data.status) { status = data.status; updatePanel(); }
  return data;
}

/**
 * The one path everything uses to change the music: chat command, sidebar
 * prompt box, and preset buttons all land here.
 */
async function steer(text, { raw = false, announce = true } = {}) {
  if (!canSteer()) {
    ui.notifications?.warn("You do not have permission to change the music.");
    return null;
  }
  const data = await sendPrompt(text, { raw });
  if (announce && setting("announceInChat")) {
    // Everyone should see why the music changed, so this one is public.
    await ChatMessage.create({
      content: `<p>🎵 <i>${esc(text)}</i><br><b>${esc(data.style ?? text)}</b></p>`,
      speaker: { alias: "Music" }
    });
  }
  // Everyone should be at the live edge for the change they just asked for.
  game.socket.emit(SOCKET, { action: "sync" });
  syncToLive();
  return data;
}

async function retune(tuning) {
  if (!canSteer()) {
    ui.notifications?.warn("You do not have permission to change the music.");
    return null;
  }
  return sendPrompt("", { tuning });
}

/* -------------------------------------------------------- sidebar panel */

/** The Playlists tab is where a listener looks for a transport, so build one. */
function panelHTML() {
  const connected = !!status;
  const playing = !!audio && !audio.paused;
  const style = status?.prompt ?? (serverUrl() ? "Not connected" : "No server URL set");
  const steerable = canSteer();
  const isGM = game.user.isGM;
  const muted = !setting("enabled");
  const lag = liveLag();

  const stateLabel = !serverUrl() ? "unconfigured"
    : !connected ? "offline"
    : armed ? "click to start"
    : !tablePlaying() ? "stopped by the GM"
    : muted ? "muted for you"
    : playing ? "live" : "connecting";

  const meta = connected
    ? `${status.listeners ?? 0} listener${status.listeners === 1 ? "" : "s"}`
      + (playing ? ` &middot; ${lag.toFixed(1)}s behind` : "")
      + (status.llm ? "" : " &middot; no LLM")
    : "music server unreachable";

  const presets = parsePresets().map((p, i) =>
    `<button type="button" class="mm-preset" data-mm="preset" data-index="${i}"
             data-tooltip="${esc(p.style)}">${esc(p.label)}</button>`).join("");

  const advanced = status ? `
    <details class="mm-advanced" ${draft.advanced ? "open" : ""}>
      <summary>Generation settings</summary>
      <div class="mm-knobs">
        ${knobHTML("morph", "Cross-fade", status.morph, 0, 10, 0.2, "s")}
        ${knobHTML("temp", "Temperature", status.temp, 0.1, 2.5, 0.05, "")}
        ${knobHTML("cfg", "Style strength", status.cfg, 0, 8, 0.25, "")}
      </div>
      <div class="mm-diag">model ${esc(status.model)} &middot;
        gen ${esc(status.gen)}&times; realtime &middot;
        buffer ${esc(status.buffer)}s</div>
    </details>` : "";

  return `
  <header class="playlist-header mm-header">
    <i class="fa-solid fa-tower-broadcast" inert></i>
    <strong>Live Music</strong>
    <span class="mm-state mm-state-${connected ? (playing ? "live" : "idle") : "off"}">${stateLabel}</span>
  </header>

  <div class="mm-now" data-tooltip="${esc(style)}">
    <i class="fa-thin fa-music" inert></i>
    <span class="mm-style ellipsis">${esc(style)}</span>
  </div>

  <div class="mm-transport flexrow">
    <button type="button" class="inline-control icon fa-solid ${playing ? "fa-pause" : "fa-play"}"
            data-mm="toggle" data-tooltip
            aria-label="${isGM ? (tablePlaying() ? "Stop for everyone" : "Play for everyone")
                              : (muted ? "Listen" : "Mute for me")}"></button>
    ${isGM ? `<button type="button" class="inline-control icon fa-solid ${muted ? "fa-volume-xmark" : "fa-headphones"}"
            data-mm="mute" data-tooltip aria-label="${muted ? "Unmute for me" : "Mute for me only"}"></button>` : ""}
    <button type="button" class="inline-control icon fa-solid fa-forward-fast" data-mm="sync"
            data-tooltip aria-label="Jump to the live edge" ${playing ? "" : "disabled"}></button>
    <i class="volume-icon fa-fw fa-solid fa-volume-low" inert></i>
    <input type="range" class="mm-volume" min="0" max="1" step="0.05"
           value="${setting("volume")}" aria-label="Live music volume">
  </div>

  <div class="mm-meta">${meta}</div>

  ${steerable ? `
  <div class="mm-steer flexrow">
    <input type="text" class="mm-prompt" placeholder="what is happening?" value="${esc(draft.text)}">
    <button type="button" class="inline-control icon fa-solid fa-paper-plane" data-mm="send"
            data-tooltip aria-label="Change the music"></button>
  </div>
  <label class="mm-raw"><input type="checkbox" data-mm="raw" ${draft.raw ? "checked" : ""}>
    exact words (skip the AI rewrite)</label>
  <div class="mm-presets">${presets}</div>
  ${advanced}` : ""}`;
}

function knobHTML(key, label, value, min, max, step, unit) {
  return `<label class="mm-knob">
    <span>${label}</span>
    <input type="range" data-mm="knob" data-key="${key}" min="${min}" max="${max}"
           step="${step}" value="${value ?? min}">
    <output>${value ?? "-"}${unit}</output>
  </label>`;
}

function updatePanel() {
  if (!panel?.isConnected) { panel = null; return; }
  // Don't yank the prompt box out from under someone mid-sentence.
  const active = panel.contains(document.activeElement) ? document.activeElement : null;
  if (active?.classList.contains("mm-prompt")) {
    draft.text = active.value;
    return;  // redraw once they are done typing
  }
  if (active?.type === "range") return;
  panel.innerHTML = panelHTML();
}

function onPanelClick(event) {
  const button = event.target.closest("[data-mm]");
  if (!button) return;
  const action = button.dataset.mm;

  if (action === "toggle") {
    event.preventDefault();
    const playing = !!audio && !audio.paused;
    return setPlaying(!playing);
  }
  if (action === "mute") {
    event.preventDefault();
    return game.settings.set(MODULE_ID, "enabled", !setting("enabled"));
  }
  if (action === "sync") {
    event.preventDefault();
    const lag = syncToLive({ force: true });
    ui.notifications?.info(`Skipped ${lag.toFixed(1)}s of delay.`);
    return updatePanel();
  }
  if (action === "send") {
    event.preventDefault();
    return submitDraft();
  }
  if (action === "preset") {
    event.preventDefault();
    const preset = parsePresets()[Number(button.dataset.index)];
    if (!preset) return;
    return steer(preset.style, { raw: true }).catch(reportError);
  }
}

function submitDraft() {
  const input = panel?.querySelector(".mm-prompt");
  const text = (input?.value ?? draft.text).trim();
  if (!text) return;
  draft.text = "";
  if (input) input.value = "";
  return steer(text, { raw: draft.raw }).catch(reportError);
}

function reportError(err) {
  log(err);
  ui.notifications?.error(`Music server: ${err.message}`);
}

function attachPanelListeners(element) {
  element.addEventListener("click", onPanelClick);

  element.addEventListener("change", (event) => {
    const target = event.target;
    if (target.classList.contains("mm-volume")) {
      return game.settings.set(MODULE_ID, "volume", Number(target.value));
    }
    if (target.dataset.mm === "raw") {
      draft.raw = target.checked;
      return;
    }
    if (target.dataset.mm === "knob") {
      draft.advanced = true;
      return retune({ [target.dataset.key]: Number(target.value) }).catch(reportError);
    }
  });

  // Live-update the slider readout and the audio while dragging, without
  // hammering the server -- the commit happens on "change".
  element.addEventListener("input", (event) => {
    const target = event.target;
    if (target.classList.contains("mm-volume")) {
      const v = Number(target.value);
      if (bus) bus.gain.gain.value = ownVolume(v);
      if (audio) audio.volume = bus ? 1 : v;
    } else if (target.dataset.mm === "knob") {
      const output = target.parentElement.querySelector("output");
      if (output) output.textContent = target.value;
    }
  });

  element.addEventListener("keydown", (event) => {
    if (event.key !== "Enter" || !event.target.classList.contains("mm-prompt")) return;
    event.preventDefault();
    submitDraft();
  });

  element.addEventListener("focusout", (event) => {
    if (event.target.classList.contains("mm-prompt")) draft.text = event.target.value;
  });
}

/** Insert the transport into the Playlists ("Music") sidebar tab. */
function injectPanel(root) {
  if (!root) return;
  root.querySelectorAll(`.${MODULE_ID}-panel`).forEach(el => el.remove());

  const element = document.createElement("div");
  element.classList.add(`${MODULE_ID}-panel`, "global-control");
  element.innerHTML = panelHTML();
  attachPanelListeners(element);

  // Sit directly above the global volume sliders when they exist, so the two
  // read as one block of audio controls; otherwise just go first.
  const anchor = root.querySelector(".global-volume") ?? root.querySelector(".directory-list");
  if (anchor) anchor.parentElement.insertBefore(element, anchor);
  else root.prepend(element);

  panel = element;
  ensureStatusPolling();
}

function ensureStatusPolling() {
  if (statusTimer) return;
  fetchStatus();
  statusTimer = setInterval(() => {
    // Polling exists to keep the panel truthful; stop when nobody can see it.
    if (!panel?.isConnected) {
      clearInterval(statusTimer);
      statusTimer = null;
      return;
    }
    fetchStatus();
  }, STATUS_POLL_MS);
}

/* --------------------------------------------------------------- commands */

const COMMAND_HELP =
  `<p><b>/music &lt;what is happening&gt;</b> — adapt the soundtrack.<br>` +
  `<b>/music raw &lt;style&gt;</b> — skip the AI rewrite.<br>` +
  `<b>/music status</b> — what is playing.<br>` +
  `<b>/music play</b> / <b>pause</b> — for the table if you are the GM, else for you.<br>` +
  `<b>/music on</b> / <b>off</b> — your own playback only.<br>` +
  `<b>/music sync</b> — jump to the live edge.<br>` +
  `<b>/music volume 0.4</b> — your own volume.<br>` +
  `<b>/music morph 3</b> — cross-fade seconds.<br>` +
  `<b>/music temp 1.2</b> / <b>cfg 3</b> — generation knobs.<br>` +
  `<b>/music llm on|off</b> — prompt rewriting.<br>` +
  `<b>/music presets</b> — list the configured presets.</p>`;

async function handleMusicCommand(argument) {
  const arg = (argument ?? "").trim();

  try {
    if (!arg || arg === "help") return postLocal(COMMAND_HELP);

    if (arg === "off") return game.settings.set(MODULE_ID, "enabled", false);
    if (arg === "on") return game.settings.set(MODULE_ID, "enabled", true);
    if (arg === "pause" || arg === "stop") return setPlaying(false);
    if (arg === "play" || arg === "resume") return setPlaying(true);

    if (arg === "sync") {
      const lag = syncToLive({ force: true });
      return postLocal(`<p>Skipped ${lag.toFixed(1)}s of buffered delay.</p>`);
    }

    if (arg === "presets") {
      const presets = parsePresets();
      if (!presets.length) return postLocal(`<p>No presets are configured.</p>`);
      return postLocal(`<p>${presets.map(p =>
        `<b>${esc(p.label)}</b> — ${esc(p.style)}`).join("<br>")}</p>`);
    }

    if (arg === "status") {
      const data = await fetchStatus({ quiet: false });
      return postLocal(
        `<p>🎵 <b>${esc(data.prompt)}</b><br><i>${data.listeners} listener(s), ` +
        `model ${esc(data.model)}, rewriter ${esc(data.llm ?? "off")}, ` +
        `cross-fade ${esc(data.morph)}s, your delay ${liveLag().toFixed(1)}s</i></p>`);
    }

    const volume = arg.match(/^vol(?:ume)?\s+([\d.]+)$/i);
    if (volume) {
      const value = Math.max(0, Math.min(1, Number(volume[1])));
      await game.settings.set(MODULE_ID, "volume", value);
      return postLocal(`<p>Your music volume is now ${Math.round(value * 100)}%.</p>`);
    }

    // The tuning knobs all take one number and read back the same way.
    const knob = arg.match(/^(morph|temp|topk|cfg)\s+([\d.]+)$/i);
    if (knob) {
      const data = await retune({ [knob[1].toLowerCase()]: Number(knob[2]) });
      if (!data) return;
      return postLocal(`<p>${esc(knob[1])} is now ` +
        `${esc(data.status?.[knob[1].toLowerCase()] ?? knob[2])}.</p>`);
    }

    const llm = arg.match(/^llm\s+(on|off)$/i);
    if (llm) {
      const data = await retune({ llm: llm[1].toLowerCase() === "on" });
      if (!data) return;
      return postLocal(`<p>Prompt rewriting is ` +
        `${data.status?.llm ? `on (${esc(data.status.llm)})` : "off"}.</p>`);
    }

    const raw = /^raw\s+/i.test(arg);
    const text = raw ? arg.replace(/^raw\s+/i, "").trim() : arg;
    if (!text) return;
    await steer(text, { raw });
  } catch (err) {
    log(err);
    postLocal(`<p>Music server unreachable (${esc(err.message)}). ` +
      `Check the URL in module settings: <code>${esc(serverUrl() || "(not set)")}</code></p>`);
  }
}

function postLocal(content) {
  return ChatMessage.create({
    content,
    speaker: { alias: "Music" },
    whisper: [game.user.id]
  });
}

/**
 * Reduce a chat message to plain text.
 *
 * Foundry's chat input is rich text, so what reaches the chatMessage hook is
 * HTML -- "/music they enter the dungeon" arrives as
 * "<p>/music they enter the dungeon</p>". Matching the raw string against a
 * /^\/music/ pattern therefore never fires, and the command falls through to
 * Foundry's "invalid command" error.
 */
function plainText(message) {
  const template = document.createElement("template");
  template.innerHTML = String(message ?? "");
  template.content.querySelectorAll("br").forEach(br => br.replaceWith("\n"));
  return template.content.textContent.trim();
}

const MUSIC_PATTERN = /^\/music\b\s*([^]*)$/i;

/* ----------------------------------------------------------------- hooks */

Hooks.once("init", () => {
  game.settings.register(MODULE_ID, "serverUrl", {
    name: "Music server URL",
    hint: "Where stream_player.py --serve is reachable from players' browsers. " +
          "Must use the same scheme as Foundry itself: an https Foundry page " +
          "cannot load an http stream.",
    scope: "world",
    config: true,
    type: String,
    default: `${window.location.protocol}//${window.location.hostname}:30001`,
    onChange: () => { busDisabled = false; fetchStatus(); refreshPlaybackState(); }
  });

  game.settings.register(MODULE_ID, "serverToken", {
    name: "Music server token",
    hint: "Must match --serve-token on the machine running stream_player.py. " +
          "Required whenever that machine is reachable from the internet; " +
          "leave blank if it is not.",
    scope: "world",
    config: true,
    type: String,
    default: "",
    onChange: () => { fetchStatus(); refreshPlaybackState(); }
  });

  game.settings.register(MODULE_ID, "steerPermission", {
    name: "Who can change the music",
    hint: "Everyone at the table, trusted players and up, or the GM alone.",
    scope: "world",
    config: true,
    type: String,
    choices: {
      everyone: "Everyone",
      trusted: "Trusted players and GMs",
      gm: "GMs only"
    },
    default: "everyone",
    onChange: () => updatePanel()
  });

  game.settings.register(MODULE_ID, "announceInChat", {
    name: "Announce music changes in chat",
    hint: "Post a public message showing the scene and the style it became. " +
          "Turn off for a quieter chat log; the music still changes.",
    scope: "world",
    config: true,
    type: Boolean,
    default: true
  });

  game.settings.register(MODULE_ID, "presets", {
    name: "Preset buttons",
    hint: "One per line, as \"Label | style prompt\". These appear as buttons " +
          "in the Music sidebar tab and are sent as exact words, no rewrite.",
    scope: "world",
    config: true,
    type: String,
    default: DEFAULT_PRESETS,
    onChange: () => updatePanel()
  });

  // Table-wide transport state. World-scoped so a GM pressing stop stops the
  // music for the whole table, and so the state survives a reload.
  game.settings.register(MODULE_ID, "playback", {
    scope: "world",
    config: false,
    type: String,
    default: "playing",
    onChange: () => refreshPlaybackState()
  });

  game.settings.register(MODULE_ID, "enabled", {
    name: "Play the live music",
    hint: "Turn off to silence the stream for yourself only.",
    scope: "client",
    config: true,
    type: Boolean,
    default: true,
    onChange: () => refreshPlaybackState()
  });

  game.settings.register(MODULE_ID, "volume", {
    name: "Music volume",
    hint: "Your own level, on top of the global Music slider in the Playlists tab.",
    scope: "client",
    config: true,
    type: Number,
    range: { min: 0, max: 1, step: 0.05 },
    default: 0.5,
    onChange: () => applyVolume()
  });

  game.settings.register(MODULE_ID, "useMusicBus", {
    name: "Route through Foundry's Music channel",
    hint: "Makes the core Music volume slider control the stream. Needs the " +
          "music server to send CORS headers, which it does by default; the " +
          "module falls back to direct playback automatically if it cannot.",
    scope: "client",
    config: true,
    type: Boolean,
    default: true,
    onChange: () => { busDisabled = false; refreshPlaybackState(); }
  });

  game.settings.register(MODULE_ID, "autoSync", {
    name: "Keep up with the live edge",
    hint: "Periodically skip buffered audio so you hear changes as soon as " +
          "everyone else. Turn off if the skips are audible on your connection.",
    scope: "client",
    config: true,
    type: Boolean,
    default: true
  });

  // Foundry v14 parses chat commands from a registry. Registering here means
  // /music is a real command rather than something intercepted after the fact.
  const ChatLog = foundry.applications?.sidebar?.tabs?.ChatLog;
  if (ChatLog?.CHAT_COMMANDS) {
    ChatLog.CHAT_COMMANDS.music = {
      rgx: MUSIC_PATTERN,
      fn: (command, match) => {
        handleMusicCommand(plainText(match[1]));
        return false;  // don't post the raw "/music ..." text
      }
    };
  }
});

Hooks.once("ready", () => {
  game.socket.on(SOCKET, (data) => {
    if (data?.action === "sync") {
      startPlayback();     // no-op if already playing
      if (setting("autoSync")) syncToLive();
    }
  });

  refreshPlaybackState();
  fetchStatus();
  log("ready; streaming from", serverUrl() || "(no URL configured)");
});

// Keep in step with the core Music slider when we are not routed through it.
Hooks.on("globalPlaylistVolumeChanged", () => { if (!bus) applyVolume(); });

// The Playlists tab is the "music" tab, so the transport belongs there.
Hooks.on("renderPlaylistDirectory", (app, element) => {
  injectPanel(element instanceof HTMLElement ? element : element?.[0]);
});

// Pre-v14 Foundry has no command registry; intercept the message instead.
// In v14 this hook still runs first and handles the command, which is fine --
// the registry entry above is the fallback, not the other way round.
Hooks.on("chatMessage", (chatLog, message) => {
  const match = plainText(message).match(MUSIC_PATTERN);
  if (!match) return true;
  handleMusicCommand(match[1] ?? "");
  return false;  // stop Foundry from posting the raw "/music ..." text
});
